### ISSUE TITLE
Board, Section, Sticker 컴포넌트 분리하기

### ISSUE THREAD

**Issue by xhseb** [innovationacademy-kr/42dashboard#38]
## TODO
- [ ]  Sticker를 선택했을 때 Section이 선택되지 않도록 하기
- [ ] Section 크기가 감소될 때 Sticker가 존재하면 그 크기보다 더이상 줄어들지 않도록 하기
- [ ] Section 크기가 변경되었을 때 Sticker가 움직일 수 있는 범위 바꿔주기
- [ ] Sticker에 차트 추가
- [ ] Sticker 컴포넌트화
---

## 06/21
- [x]  Board를 grid로 바꾸고 컴포넌트화
- [x]  Section을 grid로 바꾸고 컴포넌트화
    - [x]  gridItemWrapper, GridItemContent가 필요한지, 생각해보고 삭제하기
 - [x]  Sticker를 선택했을 때 Section이 선택되지 않도록 하기 [🔗](https://github.com/react-grid-layout/react-grid-layout/issues/575)

## 06/22
- [x] Sticker 컴포넌트 따로 생성

## 06/23
- [x] Sticker의 크기를 Section의 크기 이하만큼만 조절할 수 있도록 하기
  -> getBoundingClientRect().height를 구해서 useCallback으로 자식 props로  전달함
  - [ ] Sticker가 두줄 있다면 어떻게 할지 고민중
